licencia

diff --git a/ksm b/ksm
--- a/ksm
+++ b/ksm
@@ -1,4 +1,10 @@
 #!/bin/bash
+# Made by Sinfallas <sinfallas@yahoo.com>
+# Licence: GPL-2
+if [[ $USER != root ]]; then
+	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+	exit 1
+fi
 echo "1" > /sys/kernel/mm/ksm/run
 echo "20000" > /sys/kernel/mm/ksm/pages_to_scan
 echo "200" > /sys/kernel/mm/ksm/sleep_millisecs
